version: '3'

services: 
    api:
        build: .
        environment: 
            REDIS_URL: ""
        depends_on: 
            - redis
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src
            - /usr/src/node_modules


    redis:
        image: redis

    # rabbitmq:
    #    image: 