version: '3'

services: 
    api:
        build: .
        environment: 
            REDIS_URL: ""
        depends_on: 
            - redis


    redis:
        image: redis

    # rabbitmq:
    #    image: 